### ISSUE TITLE
region_type_plugin_sd_apex_mermaid_diagrams.sql file is not a proper sql file

### ISSUE THREAD

**Issue by DanielWenz** [sdembele/apex_mermaid_diagram#2]
I checked this plugin several times and tried to have a deeper lock into but always when it try to download it, i just got a html file. 

It seems the region_type_plugin_sd_apex_mermaid_diagrams.sql file is not a proper sql file.

Is there a way you can check and fix it?

**Comment by sdembele** [comment]
Fixed

Le lun. 11 janv. 2021 à 16:01, DanielWenz <notifications@github.com> a
écrit :
